"""
Base Strategy
Abstract base class for all QuantBot trading strategies.
"""

import logging
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional
import pandas as pd

logger = logging.getLogger(__name__)


class SignalAction(str, Enum):
    """Possible trading signal actions."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class Signal:
    """
    Represents a trading signal generated by a strategy.

    Attributes:
        action:     BUY, SELL, or HOLD.
        asset:      Symbol for the asset (e.g. "AAPL").
        confidence: Float in [0.0, 1.0] indicating signal strength.
        reasoning:  Human-readable explanation of the signal.
        metadata:   Optional dict of strategy-specific indicators.
    """
    action: SignalAction
    asset: str
    confidence: float
    reasoning: str
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(
                f"Signal confidence must be in [0.0, 1.0], got {self.confidence}"
            )


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    Subclasses must implement `generate_signal`.
    """

    def __init__(self, name: str) -> None:
        self.name = name
        self.logger = logging.getLogger(f"{__name__}.{name}")

    @abstractmethod
    def generate_signal(self, price_df: pd.DataFrame, symbol: str) -> Signal:
        """
        Generate a trading signal from price data.

        Args:
            price_df: DataFrame with columns: open, high, low, close, volume.
                      Index should be a DatetimeIndex.
            symbol:   Ticker symbol this data belongs to.

        Returns:
            A Signal instance.
        """
        ...

    def validate_signal(self, signal: Signal) -> bool:
        """
        Validate that a signal is well-formed.

        Returns True if valid, False (and logs a warning) if not.
        """
        if signal.action not in SignalAction:
            self.logger.warning("Invalid action: %s", signal.action)
            return False

        if not isinstance(signal.asset, str) or not signal.asset.strip():
            self.logger.warning("Signal has empty/invalid asset.")
            return False

        if not 0.0 <= signal.confidence <= 1.0:
            self.logger.warning(
                "Signal confidence %.2f out of range [0,1].", signal.confidence
            )
            return False

        return True

    def _ensure_columns(
        self, df: pd.DataFrame, required: list[str]
    ) -> Optional[pd.DataFrame]:
        """
        Check that required columns exist in the DataFrame.

        Returns the DataFrame if valid, or None if columns are missing.
        """
        missing = [c for c in required if c not in df.columns]
        if missing:
            self.logger.warning(
                "DataFrame missing required columns: %s", missing
            )
            return None
        return df

    def _hold_signal(self, symbol: str, reason: str) -> Signal:
        """Return a HOLD signal with a given reason."""
        return Signal(
            action=SignalAction.HOLD,
            asset=symbol,
            confidence=0.0,
            reasoning=reason,
        )
